const categories=[
{name:'हार',desc:'Royal Necklace Designs',icon:'💎',key:'necklace'},
{name:'कड़े',desc:'Elegant Kade & Bangles',icon:'✨',key:'bangles'},
{name:'अंगूठियाँ',desc:'Beautiful Ring Collection',icon:'💍',key:'rings'},
{name:'मांग टीका',desc:'Bridal Maang Tikka',icon:'👑',key:'maang-tikka'},
{name:'नाथ',desc:'Traditional Nose Rings',icon:'🌸',key:'nath'},
{name:'पायल',desc:'Traditional Payal',icon:'✨',key:'payal'},
{name:'बाजूबंद',desc:'Royal Bajuband',icon:'〰️',key:'bajuband'},
{name:'माथा पट्टी',desc:'Bridal Matha Patti',icon:'👑',key:'matha'}];
const silverPrices=[199,299,399], goldPrices=[499,599,699];
let products=[],cart=JSON.parse(localStorage.getItem('baisaCart')||'[]'),activeCategory=null,activeMetal='All';
function createProducts(){let id=1;for(const c of categories){for(let i=1;i<=50;i++){products.push({id:id++,category:c.name,key:c.key,metal:'Silver',name:`${c.name} Silver Design ${String(i).padStart(2,'0')}`,price:silverPrices[(i-1)%3],image:`images/${c.key}-silver-${String(i).padStart(3,'0')}.svg`,desc:`Premium Silver finish ${c.name} design.`});}for(let i=1;i<=50;i++){products.push({id:id++,category:c.name,key:c.key,metal:'Gold',name:`${c.name} Gold Design ${String(i).padStart(2,'0')}`,price:goldPrices[(i-1)%3],image:`images/${c.key}-gold-${String(i).padStart(3,'0')}.svg`,desc:`Premium Gold finish ${c.name} design.`});}}}
function filtered(){let list=products;if(activeCategory!==null)list=list.filter(p=>p.key===categories[activeCategory].key);if(activeMetal!=='All')list=list.filter(p=>p.metal===activeMetal);const q=document.getElementById('search').value.toLowerCase().trim();if(q)list=list.filter(p=>(p.name+' '+p.category+' '+p.metal).toLowerCase().includes(q));return list;}
function renderCategories(){document.getElementById('categoryGrid').innerHTML=categories.map((c,i)=>`<button class="categoryCard" onclick="showCategory(${i})"><div class="categoryIcon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p><small>100 Designs<br>50 Silver + 50 Gold</small></button>`).join('');}
function renderProducts(){const list=filtered();document.getElementById('productInfo').textContent=`${list.length} Designs`;document.getElementById('productGrid').innerHTML=list.length?list.map(p=>`<article class="productCard" onclick="openProduct(${p.id})"><img src="${p.image}" alt="${p.name}" loading="lazy"><div class="productBody"><div class="productCat">${p.category} • ${p.metal}</div><div class="productName">${p.name}</div><div class="productBottom"><span class="price">₹${p.price}</span><button class="addBtn" onclick="event.stopPropagation();addToCart(${p.id})">Add</button></div></div></article>`).join(''):`<div class="empty">कोई Design नहीं मिला ❤️</div>`;}
function updateTitle(){document.getElementById('collectionTitle').textContent=activeCategory===null?'खास Jewellery Collection — 800 Designs':`${categories[activeCategory].name} — 100 Designs`+(activeMetal==='All'?'':` • ${activeMetal}`);}
function showCategory(i){activeCategory=i;activeMetal='All';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.metal==='All'));updateTitle();renderProducts();document.getElementById('collection').scrollIntoView({behavior:'smooth'});}
function showAll(){activeCategory=null;activeMetal='All';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.metal==='All'));updateTitle();renderProducts();document.getElementById('collection').scrollIntoView({behavior:'smooth'});}
function addToCart(id){const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});saveCart();alert('Jewellery Cart में Add हो गई ❤️');}
function saveCart(){localStorage.setItem('baisaCart',JSON.stringify(cart));updateCartCount();}
function updateCartCount(){document.getElementById('cartCount').textContent=cart.reduce((n,i)=>n+i.qty,0);}
function cartTotal(){return cart.reduce((s,i)=>{const p=products.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0)}
function openCart(){renderCart();document.getElementById('cartModal').classList.remove('hidden');}
function renderCart(){const box=document.getElementById('cartItems');if(!cart.length){box.innerHTML='<div class="empty">आपका Cart खाली है ❤️</div>';document.getElementById('cartTotal').textContent='₹0';document.getElementById('paymentAmount').textContent='₹0';return;}box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cartItem"><img src="${p.image}" alt=""><div class="cartInfo"><b>${p.name}</b><div>₹${p.price} × ${i.qty}</div><button class="remove" onclick="changeQty(${p.id},-${i.qty})">Remove</button></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${p.id},1)">+</button></div></div>`}).join('');document.getElementById('cartTotal').textContent='₹'+cartTotal().toLocaleString('en-IN');document.getElementById('paymentAmount').textContent='₹'+cartTotal().toLocaleString('en-IN');}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);saveCart();renderCart();}
function checkout(){if(!cart.length){alert('पहले Jewellery Add करें ❤️');return;}document.getElementById('paymentAmount').textContent='₹'+cartTotal().toLocaleString('en-IN');closeModal('cartModal');document.getElementById('payment').scrollIntoView({behavior:'smooth'});}
function paymentDone(){if(!cart.length){alert('पहले Cart में Jewellery Add करें ❤️');return;}let lines=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `${p.name} x ${i.qty} = ₹${p.price*i.qty}`}).join('\n');const msg=`Hello Baisa Ka Singar,\n\nमैंने Online Payment किया है.\n\nOrder:\n${lines}\n\nTotal: ₹${cartTotal().toLocaleString('en-IN')}\n\nPayment Screenshot भेज रहा/रही हूँ.`;window.open('https://wa.me/917568496499?text='+encodeURIComponent(msg),'_blank');}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.getElementById('modalImg').src=p.image;document.getElementById('modalName').textContent=p.name;document.getElementById('modalCat').textContent=`${p.category} • ${p.metal}`;document.getElementById('modalDesc').textContent=p.desc;document.getElementById('modalPrice').textContent='₹'+p.price;document.getElementById('modalAdd').onclick=()=>{addToCart(p.id);closeModal('productModal')};document.getElementById('productModal').classList.remove('hidden');}
function closeModal(id){document.getElementById(id).classList.add('hidden');}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{activeMetal=b.dataset.metal;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));updateTitle();renderProducts();}));
document.getElementById('search').addEventListener('input',renderProducts);document.getElementById('cartOpen').addEventListener('click',openCart);document.getElementById('checkoutBtn').addEventListener('click',checkout);document.getElementById('paidBtn').addEventListener('click',paymentDone);window.addEventListener('click',e=>{if(e.target.classList.contains('modal'))e.target.classList.add('hidden')});
createProducts();renderCategories();renderProducts();updateCartCount();
